### ISSUE TITLE
Update mock data #1.

### ISSUE THREAD

**Issue by pedroluizmcs** [UIoT/uiot_data#5]
Mock data must be updated to be used with newest Database model. (commit [`8919199a2042437b30eb6ade99c2b2b2d0ed16d6`](https://github.com/UIoT/middleware_mc_srvcl_big_data/commit/8919199a2042437b30eb6ade99c2b2b2d0ed16d6))

**Comment by pedroluizmcs** [comment]
Solved with commit 65e4175 . Thanks for the tip, Claudio!

**Comment by masterl** [comment]
Better yet:
When commiting, you should put the issue number on the commit, like:
"Updates database model #5"

So it appears like this:
![screenshot_2016-05-06_14-41-20](https://cloud.githubusercontent.com/assets/5068286/15081288/a6598906-1398-11e6-99b2-40a40d057678.png)
